feature6/another-file.txt, feature6/new-file.txt
Created two files inside feature-6 folders.
=> [Feature 6] New feature 6 was implemented.

feature555/newfile.txt, feature555/otherfile.txt
=> [Feature 555] new feature 555 implemented

feature7/another-file.txt, feature7/new-file.txt
I have created new folder `feature7`  with two files
=> [Feature7] New feature 7 was implemented

featureA/another-file.txt, featureA/new-file.txt
I have created a new folder `featureA` with two files
=> [featureA] New feature A was implemented

feature7/quote/about.tx, feature7/quote/dev.txt
Added a quote folder with an example quote file and an about file.
=> [feature7] Quote folder added

feature07/another-file.txt, feature07/new-file.txt
I have created new folder "feature07" with two files
=> [Feature07] new feature07 was implemented

feature05/another-file.txt, feature05/new-file.txt
Created feature05 branch with 2 new files. Please review and merge to your master branch. 
Thank you.
=> [feature05] New feature05 was implemented

feature69/new-file.txt, feature69/other-file.txt
I have created new folder with two files
=> [Feature69] New feature69 was implemented 

feature10/new-file.txt
The new folder `feature10` was created.
=> [feature10] New feature 10 was implemented

feature24/cool-new_testing.txt, feature24/new_test.txt
=> [feature24] Another pull_request testing

feature100/another-file.txt, feature100/new-file.txt
I have created feature100 branch with 2 files 
- new-file.txt
- another-file.txt
=> [Feature100] New feature100 was implemented

feature555/another-file.txt, feature555/new-file.txt
I have created neew folder 'feature' with two files
=> [Feature555] New featur555 was implemented 

feature-0/another-file.txt, feature-0/new-file.txt
I have created new folder `feature-0` with two files
=> [feature-0] feature-0 was implemented

feature666/another-file.txt, feature666/new-file.txt
I have created new folder `feature666` with two files
=> [Feature666] - New feature 666 was implemented

feature090/another-file.txt, feature090/new-file.txt
I have created a new folder `feature090` with two files
=> [feature090] New feature 090 was implemented

feature536/another-file.txt, feature536/new-file.txt
I have created new folder `feature536` with two files
=> [feature536] New feature 536 was implemented

feature1228/another-file.txt, feature1228/new-file.txt
i have created new folder `feature1228` and added 2 files
=> [Feature1228]new feature 5 was implemented

feature999/another-file.txt, feature999/new-file.txt
I have created new folder 'feature999' with two files
=> [Feature999]new feature999 was implemented

feature-x/another-file.txt, feature-x/nex-file.txt
I have created a new folder `feature-x` including two files.
=> [feature-x] New feature-x was implemented 

feature-shri-1/another-file.txt, feature-shri-1/new-file.txt
As instructed, I have created 2 files in this new exceptional feature
`1. file-1.txt`
`2. file-2.txt`
=> [feature-shri-1] New exceptional feature-shri-1 was created :-P

feature-o/another-file-o.txt, feature-o/new-file-o.txt
I have created new folder 'feature-o' with two files
=> [feature-o] New feature-o was implemented

feature11/another-file.txt, feature11/new-file.txt
Create new folder `feature11` with two files
=> [feature11] New feature11 was implemented

feature-001/1st-file.txt, feature-001/2nd-file.txt
Pull request from tysongithubber to mikegithubber. Next edits ere done:
- added file `1st-file.txt`
- added file `2nd-file.txt`
=> [feature-001] Added some files

features199/another-file.txt, features199/new-file.txt
I have created new folder `feature199` with two files
=> [Feature199] new. feature 199 was implemented

feature1966/another-file.txt, feature1966/new-file.txt
Create a new folder `feature1966` with two files
=> [feature1966] New feature 1966 was implemented

feature152/another-new-file.txt, feature152/new-file.txt
Created feature152 with two files
=> [feature152] Feature 152 was implemented

feature-pl-1/another-file.txt, feature-pl-1/new-file.txt
Features added are below
- new-file.txt was added
-another-file.txt was added
=> [feature-pl-1] New feature was implemented

feature-2000/another-file.txt, feature-2000/new-file.txt
I have created new folder `feature-2000` with 2 files containing different song lyrics instead of filler text. See if you can work out what songs they're from.
=> [Feature-2000] new feature 2000 was implemented

feature25/feature25.txt
Hello, Bogdan! I made this pull request as instructed in the course.
Created new folder `feature25` and a file inside it (`feature25.txt`)
Nice course, btw!
=> [feature25] Feature25

feature-9000/new-file.txt
I have created new folder `feature-9000` with one file
=> [feature-9000] New feature 9000 was implemented

feature2020/another-file.txt, feature2020/new-file.txt
I have created new folder `feature2020` with two files
=> [feature2020] New feature 2020 was implemented

feature67/another-file.txt, feature67/new-feature.txt
Changes made 
- feature67 folder created
- 2 new files added
=> [Feature67] Feature67 added. Created one folder and two new files.

feature55/another-file.txt, feature55/new-file.txt
I have created new folder 'feature55'  with two files
=> [feature5] New feature5 was implemented

feature767/another-file.txt, feature767/new-file.txt
I have created a new folder `feature767` with two files
=> [feature767] New feature 767 was implemented

feature777/another-file.txt, feature777/new-file.txt
=> [Feature777] New feature 777

feature-n/another-file.txt, feature-n/new-file.txt
I have created new folder `feature-n` with two files
=> [feature-n] New feature n was implemented

feature999/another-file999.txt, feature999/new-file999.txt
I have created new folder `feature999` with two files
=> [feature999] New feature 999 was implemented

mybranch/another.txt, mybranch/new.txt
=> Feature5 new feture

feature233/bla.txt, feature233/nothing.txt
I created folder feature223 folder with two files
=> [Feature233] feature223 was implemented 

feature22/another-file.txt, feature22/new-file.txt
=> [Feature22] Feature 22 was implemented

feature55/new-file55.txt
=> [feature55] Feature55 was implemented

feature40/another-file.txt, feature40/new-file.txt
I have created new folder `feature40` with two files
=> [Feature40] New feature 40 was implemented

feature77/another-file.txt, feature77/new-file.txt
I have created new folder `feature77` with 2 files
=> {feature77] New feature 77 was implemented

feature5_ps/another-file.txt, feature5_ps/new-file.txt
I have created new folder 'feature5' with two files
=> [feature5_ps] New feature 5 was implemented

feature012/feature012A.txt, feature012/feature012B.txt
The following files were created:
- `feature012/feature012A.txt`
- `feature012/feature012B.txt`
=> [feature012] Exercise about opening a pull request after ending section 12 of the course

feature453/new-file.txt, feature453/other-file.txt
I have implemented `new feature`.
=> [feature453] Added some files to implement feature 453

feature007/bond-file.txt
From complete Git guide which is a great course ! You rock Bogdan !
=> [feature007] New feature 007 was implemented

feature-2020-11-25/another-dummy-file.txt
some notes about the implemented feature here... bablababla
-> Hello Bogdan, I'm enjoying your course about git and GitHub.. It's great!!!
=> [feature-2020-11-25] Added another-dummy-file.txt

feature-92/another-file.txt, feature-92/new-file.txt
I have created new folder `feature-92` with two files
=> [Feature-92] New feature 92 was implemented

feature1420/another-file.txt, feature1420/new-file.txt
i have created new folder 'feature1420'
=> [Feature-1420] new feature 1420

feature-a/newfeature.txt
=> Feature ly

feature_13/feature_13_file.txt, feature_13/please_read.txt
I have created game changing feature_13, which consists:
- folder feature_13
- two files in same folder
Have a nice day 👍
=> [Feature_13] New feature_13 was implemented

feature-0024/another-file.txt, feature-0024/new-file.txt
I have created new folder "feature-0024" with two files
=> [Feature-0024] New feature 0024 was implemented

feature-cyber-sale/list-sale.txt
=> [feature-cyber-sale] New Feature Cyber Sale

feature-18/another-file.txt, feature-18/new-file.txt
I have created new folder `feature-18` with two files
=> [feature-18] New feature-18 was implemeted

feature192/another-file.txt, feature192/new-file.txt
I have created folder192 with two files
=> [Feature192] New feature192 was implemented

feature-555/another-file.txt, feature-555/new-file.txt
I've created new folder "Feature-555' with 2 files
=> [feature555] new feature 5 was implemented

feature88/another-important-file.txt, feature88/important-file.txt
I have created a new folder `feature88` with two files.
=> [feature88] New feature 88 was implemented.

feature-0632/another-file.txt, feature-0632/new-file.txt
Changes added:
- New folder added
- New files added(2)
=> [Feature0632] New Feature 0632 was implemented

feature123/another-file.txt, feature123/new-file.txt
Created new folder `feature123` with two files
=> [Feature123] New feature123 implemented

feature99/new-file.txt
New folder `feature99` was created and one file was added
=> [feature99] new feature99 was added

nonfeature/anothertest.csv, nonfeature/nontest.txt
Created a new branch called nonfeature
=> [Nonfeature] new nonfeature for testing

feature1221/another-file.txt, feature1221/new-file.txt
I have created new folder `feature1221` with two files
=> [feature1221] New feature 1221 was implemented

feature555/new-file-555.txt
=> [feature555] Create new-file-555.txt

feature790/another-file.txt, feature790/new-file.txt
I have created new folder 'feature790' with 2 files.
=> [feature790] New feature 790 was implemented.

caracteristica133/nuevo-archivo.txt, caracteristica133/otro-archivo.txt
Creé la nueva carpeta 'caracteristica133' con dos archivos.
=> [caracteristica133] Se implementó la nueva característica 133

feature6969/another-file.txt, feature6969/new-file.txt
I have created new folder `feature6969` with two files
=> [feature6969] New feature 6969 was implemented

feature-2021-02-03/another-file.txt, feature-2021-02-03/new-file.txt
I have created new folder `feature-2021-02-03` with two files
=> [feature-2021-02-03] New feature-2021-02-03 was implemented

feature-2021-01-29/another-file.txt, feature-2021-01-29/new-file.txt
I have created new folder `feature-2021-01-29` with two files.
=> [feature-2021-01-29] New feature-2021-01-29 was implemented

feature1357/another-file.txt, feature1357/new-file.txt
I have created new folder `feature1357` with two files
=> [feature1357] New feature 1357 was implemented

feature21032021/another-file.txt, feature21032021/new-file.txt
I have created new folder with two files
=> [feature5] New feature 5 was implemented

feature-2021-03/new-file.txt
=> [feature-2021-03] New feature 5 was implemented

feature88/another-file.txt, feature88/newfile.txt
Created 2 files and new folder
=> [Feature88] New feature 88 was implemented

feature-01-pret/another-file.txt, feature-01-pret/new-file.txt
I have created a new folder with 2 new files in it.
=> [feature01-pret] New feature is implemented to create pull requests to parent repository

feature-2021-03-10/another-file.txt, feature-2021-03-10/new-file.txt
I have created new folder 'feature-2021-03-10' with two files in it
=> [Feature-2021-03-10] New feature-2021-03-10 was implemented

feature2021-5-13/another-file.txt, feature2021-5-13/new-file.txt
I have created new folder `feature2021-5-13` with two files
=> [feature2021-5-13] New Feature2021-5-13 was implemented

feature130521/another-file.txt, feature130521/new-file.txt
I have created new folder `feature130521` with two files
=> [Feature 130521] New featuren130521 was implemented

feature-hm-1000/another-file.txt, feature-hm-1000/new-file.txt
I have created new folder `feature-hm-1000` with two files
=> [feature-hm-1000] Feature hm 1000 was created

feature05052021/another-file.txt, feature05052021/new-file.txt
I have created created a new folder `feature05052021` with two .txt files.
=> [feature-05-05-2021-1] new feature -05 implemented

feature-2021-05-01/another-file.txt, feature-2021-05-01/new-file.txt
I have created new folder `feature-2021-05-01` with 2 files
=> [feature-2021-05-01] New feature-2021-05-01 was implemented

feature333/another-file.txt, feature333/new-file.txt
i have created new folder feature333with 2 files
=> [Feature333]new feature333was implemented

feature_1/hello.txt, feature_1/info.txt
Two new files were added:
- hello.txt
- info.txt
=> [feature_1] feature_1 is implemented

feature-2021-03-22/another-file.txt, feature-2021-03-22/new-file.txt
Please review:
- add of new-file.txt and another-file.txt to implement feature-2021-03-22
=> [Feature-2021-03-22] : new feature-2021-03-22 was implemented

feature-99/another-file.txt, feature-99/new-file.txt
I added two more files in folder feature-99 to 'pull-requests' remote repository:
1. new-file.txt
2. another-file.txt
Greetings from Poland! Bogdan you are the best!
=> [feature-99] Two more files to 'pull-requests' remote repository

another-file.txt, new-file.txt
I made a folder with today's date and two files
=> [Feature-2021-05-19] New feature was implemented

feature50/another-file.txt, feature50/new-file.txt
I have created new folder and branch named `Feature50`
=> [feature50] Feature50 branch and folder created

feature-007/feature-007.txt
I have created a folder `feature-007`  with a file
=> [feature-007] New feature feature-007 was implemented 

a-hi-bogdan, a-hi-bogdan/another, a-hi-bogdan/new-file.txt
Hope you're having a good day!
=> [a-hi-bogdan] Added new-file.txt and another-file.txt

feature-jam/another-file.txt, feature-jam/new-file.txt
I have created new folder `feature-jam` with two files
=> [feature-jam] New Feature jam was implemented

feature5566/another-file.txt, feature5566/net-file.txt
Have created new folder folder 5566  and files 
net-file.txt
another-file.txt
=> [feature5566] New feature 5566 was implemented 

feature-108/another-file.txt, feature-108/new-file.txt
I have created a new folder with 2 files
=> [feature-108] New feature 108 was implemented

feature_0105/another_file.txt, feature_0105/newfile.txt
I have created a new folder `feature_0105` with two files
=> [feature_0105] new feature branch was implemented

feature-love-u-3000/another-file.txt, feature-love-u-3000/new-file.txt
=> [Feature love u 3000] - Feature love u 3000

feature-64/another-file.txt, feature-64/new-file.txt
=> [feature-64] New feature 64 was implemented

feature/another-file.txt, feature/new-file.txt
I have created new folder "feature-raj" with two files.
=> [Feature-raj] New Feature 5 was implemented

feature828/another-file.txt, feature828/new-file.txt
I have created a new folder, `feature828`, with two files
=> [feature828] new feature 828 was implemented

feature-2021-09-26/TheGreatestTextFile.txt
Changes in this branch:
1. Created TheGreatestTextFile.txt
=> [feature-2021-09-26] Create TheGreatestTextFile.txt

feature-aza/another-file.txt, feature-aza/aza.txt
=> [feature-aza] New feature added.

feature-abc123/abc123-another.txt, feature-abc123/abc123.txt
I have created new folder 'feature-abc123' with new files
=> [feature-abc123] add files to the forked branch

fea-midietec/ipsum-lorem-v02.txt, fea-midietec/ipsum-lorem.txt
At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum fuga
=> [fea-midietec] Ipsum Lorem feature implemented

feature3000/another-file.txt, feature3000/new-file.txt
I have created new folder `feature-3000` with two files
=> [feature-3000] New feature was implemented

feature12-10-2021/another-file.txt, feature12-10-2021/new-file.txt
I have created new folder `feature12-10-2021` with files `another-file.txt` and `new-file.txt`
=> [Feature12-10-2021] New feature 12-10-2021 was implemented

feature1974/another-file.txt, feature1974/new-file.txt
I've created new folder `feature1974` with two files.
=> [feature1974] New feature 1974 was implemented

feature-1-prav/another-file.txt, feature-1-prav/new-file.txt
I have created new folder 'feature-1-prav' with 2 files
=> [Feature 1 prav] New feature added by Praveen Bandla

feature93/another-file.txt, feature93/new-file.txt
Created another folder feature93 with new files
=> [feature93] New feature 93 was implemented

feature-2021-11/another-file.txt, feature-2021-11/new-file.xtx
I have created new folder with `feature-2021-11` with 2 files
=> [feature-2021-11] New feature was implimented

feature86/another-file, feature86/newfile.txt
I created new folder with two files
=> [Feature86] new feature 86 is implemented

feature-dec31-last-day-of-year-2021/another-file.txt, feature-dec31-last-day-of-year-2021/new-file.txt
Created a new folder `feature-dec31-last-day-of-year-2021` and added 2 files `new-file.txt` and `another-file.txt` in it.
=> [feature-dec31-last-day-of-year-2021] New feature implemented

feature-9999/another-file.txt, feature-9999/new-file.txt
I have created new folder `feature-9999` with two files.
=> [Feature-9999] Feature 9999 was implemented.  

feature-201221-2325/another-file201221-2325.txt, feature-201221-2325/new-file201221-2325.txt
Contributing to this repository
=> [feature 201221 2325] : New feature was implemented today

majaliwa/name.txt
=> [majaliwa] Names are important

feature2/another-file.txt, feature2/new-file.txt
I have created ne folder `feature 2` with two files
=> [Feature2] new feature2 implementated

Feature68/New-file.txt, Feature68/another-file.txt
I have created new folder `feature68` with two files
=> [Feature68] new feature 68 was implemented

feature-890/another-file.txt, feature-890/newfile.txt
I have created new folder `feature890` with two files
=> [Feature890] New feature 890 was implemented

featurepk/anotherFile.txt, featurepk/newfile.txt
=> [Newbranch] Testing branch

feature-BR-2022-05-23/another-file.txt, feature-BR-2022-05-23/new-file.txtx
- created new folder
- created two new files
=> [Feature br 2022 05 23] new feature implemented

feature-3627-6301/another-file.txt, feature-3627-6301/new-file.txt
I have created a new folder 'Feature 3627 6301' with two new files
=> [Feature 3627 6301] New feature 3627 6301 was created

feature-mcocmo62/another-file.txt, feature-mcocmo62/new-file.txt
I created a new folder an create 2 files underneath
=> [feature-mcocmo62] New feature was implemented

feature-21042022/another-file.txt, feature-21042022/new-file.txt
Test of pull requests on a fork
=> [feature-21042022] New feature was implemented

feature-5404/another-file.txt, feature-5404/new-file.txt
I have created new folder 'feature-5404' with two files
=> [feature5404] New feature 5404 was implemented

newest-file.txt, second-file.txt
I have created new folder `feature4` with two files.
=> [Feature4] New feature 4 was implemented

feature110197/another-file.txt, feature110197/new-file.txt
I have created new folder `folder110197` with two files
=> [feature110197] New feature 110197 was implemented

feature-2022-02-23/another-file.txt, feature-2022-02-23/new-file.txt
A new awesome feature was implemented. It consists of an additional folder `feature-2022-02-23`with two files.
=> [Feature-2022-02-23] New feature 2022-02-23 created

featureX/another-file.txt, featureX/new-file.txt
I have created a new folder `featureX` with 2 files
=> [FeatureX] New feature X was implemented

AddMe/MyNameIs.txt
I've created one folder with one file
=> Let's be friends

feature_987/another-file.txt, feature_987/new-file.txt
I have created new folder 'feature_987' with two files
=> [feature_987] New feature 987 was implemented

feature/new-files.txt
I have created new folder `feature5` with two files
=> [feature5]  New feature 5 was implemented

feature-5/another-file.txt, feature-5/new-file2.txt
I have created a new folder `feature5` with two files
=> [feature-new01] New Feature 5 was implemented

feature010123/another-file.txt, feature010123/new-file.txt
=> [feature 010123] new feat implemented

new_branch1/new_file1.txt, new_branch1/second_file.html
created a new folder with 2 files
=> [New branch1] new branch was created

featurebranch1/another-file.txt, featurebranch1/new-file.txt
I have created new featurebranch1 folder with 2 files:
- another-file.txt
- new-file.txt
=> [Featurebranch1] New feature featurebranch1 was implemented

feature-221208/another-file.txt, feature-221208/new-file.txt
I have created new folder feature-221208 with two files
=> [Feature 221208] New feature 221208 was implemented

feature-543/another-file.txt, feature-543/new-file.txt
Feature 543 implemented in two files.
=> Feature 543

feature-36/another-file.txt, feature-36/new-file.txt
Have a great day!
**Glory to Ukraine! Glory to Heroes!**
=> [Feature-36] New Feature-36 branch was implemented

my-demo-branch.txt
I have created new 'my-demo-branch.txt' file
=> [my-demo-branch] Create my-demo-branch.txt

featur5/another-file.txt, featur5/new-file.txt
I have created new folder 'featur5' with two files
=> [featur5] New featur5 was implemented

feature20220819/another-file.txt, feature20220819/new-file.txt
I have creadted new folder 'feature20229819' with two files
=> [Feature 20220819] new feature implemented

feature1507/another-file.txt, feature1507/new-file.txt
I have created new folder `feature1507` with two files
=> [feature1507] New feature1507 was implemented

feature-[2]/another-file.txt, feature-[2]/new-file.txt
i have  created new folder with two files
=> Feature 2]new feature file was implemented

featureeeee5/another-file.txt, featureeeee5/new-file.txt
=> [feature019] New feature 019 was implemented

feature new-1/new.txt
=> [feature-new1]Create new.txt

feature-02-21-2024/another-file.txt, feature-02-21-2024/new-file.txt
I have created a new folder `feature-02-21-2024` with two files
=> [Feature-02-21-2024] New feature-02-21-2024 was implemented

new_feature/dummy.txt
Changes were done as follows:
- New folder was created and inside it a dummy.txt file was created with some contents.
=> [Feature_YRG] new_feature folder was added

feature511/another-file.txt, feature511/new-file.txt
I have created new folder `feature511` with two files
=> [Feature511] New feature 511 was implemented

feature161123/another-file.txt, feature161123/new-file.txt
I have created new folder in feature 161123
=> [feature161123] New feature161123 was inplimented

feature_2023-11-12/another-file.txt, feature_2023-11-12/new-file.txt
I have created new folder "feature5" with two files
=> [Feature_2023-11-12] New feature 2023-11-12 was implemented

feature69420/another-file.txt, feature69420/new-file.txt
I have created new directory `feature69420` with two files
=> [feature69420] new feature 69420 was implemented

feature-audrey-5/another-file.txt, featureaudrey5/another-file.txt
I have created new folder `featureaudrey5` with two files
=> [featureaudrey5] new Featureaudrey5 was implemented

feature-20230706/new-file.txt
=> [feature-20230706]Added some new files

feature-July-4th-2023/another-file.txt, feature-July-4th-2023/new-file.txt
I'm gonna have an interview for a `Senior Kubernetes` position, wish me luck. xD
=> [Feature july 4th 2023] New feature, lets be friends my dudes

feature9546/another-file.txt, feature9546/new-file.txt
I have created new folder 'feature9546' with two files
=> [Feature9546] New feature 9546 was implemented

feature714/another-file.txt, feature714/new-file.txt
I have created new folder `feature714` with two files
=> [feature714] New feature 714 was implemented

feature-onehundred/another-file.txt, feature-onehundred/new-file.txt
I have created new folder feature-onehundred with two files.
=> [feature-onehundred] Feature-OneHundred was added
